// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CourseStructureController from "./course_structure_controller"
application.register("course-structure", CourseStructureController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import CourseDocsController from "./course_docs_controller"
application.register("course-docs", CourseDocsController)

import QuizController from "./quiz_controller"
application.register("quiz", QuizController)
